import country
import gender
import marital_status
import marital_status_gender
import education_levels
import caste
import accommodation_type
import accommodation_status
import profession
import employment_status
import religion
import country_admin_unit_type
import country_admin_unit
import worldcities
import sect
import contact_type
import person
import currency
import country_currency
import person_relationship_type


# person_relationship_type.import_person_relationship_type()
# currency.import_currencies()
# country.import_countries()
country_currency.import_country_currency()
# gender.import_genders()
# marital_status.import_marital_statuses()
# education_levels.import_education_levels()
# marital_status_gender.import_marital_status_genders()
# caste.import_castes()
# accommodation_type.import_accommodation_types()
# accommodation_status.import_accommodation_statuses()
# profession.import_professions()
# employment_status.import_employment_statuses()
# religion.import_religions()
# country_admin_unit_type.import_country_admin_unit_types()
# country_admin_unit.import_country_admin_unit()
# worldcities.import_city()
# sect.import_sect()
# contact_type.import_contact_types()
# person.import_person()
